spring:
  application:
    name: server
  zipkin:
    base-url: http://localhost:7000
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka