spring:
  application:
    name: zipkin-server
server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false