spring:
  application:
    name: client
  zipkin:
    base-url: http://localhost:7000
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
feign:
  hystrix:
    enabled: true